version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432

  web:
    ports:
      - 8080:8080
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DB_PORT=5432"
      - "DB_HOST=db"
      - "DB_NAME=payment"
      - "DB_USERNAME=payment"
      - "DB_PASSWORD=payment"
      - "ADMIN_USERNAME=admin"
      - "ADMIN_PASSWORD=admin24"
      - "OAUTH_CLIENT_USERNAME=client"
      - "OAUTH_CLIENT_PASSWORD=client24"
      - "SIGNING_KEY=zvJcsfK8qsPPp7uP3zKc8WTGhCETgF"
      - "PAYMENT_API_KEY=p7uP3zKc8WTzvJcsfK8qsPPGhCETgF"
      - "LOGGING_LEVEL_ROOT=info"
