version: "3"
services:
  web:
    ports:
      - 8080:8080
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DB_URL=jdbc:postgresql://db:5432/payment"
      - "DB_NAME=payment"
      - "DB_USERNAME=payment"
      - "DB_PASSWORD=payment"
      - "ADMIN_USERNAME=admin"
      - "ADMIN_PASSWORD=yGAmXjrcxta5wQGSe5dx"
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432
