version: "3"
services:
  web:
    ports:
      - 8080:8080
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "DB_URL=jdbc:postgresql://db:5432/payment"
      - "DB_NAME=payment"
      - "DB_USERNAME=payment"
      - "DB_PASSWORD=payment"
  keycloak:
    build: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      POSTGRES_ADDR: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DATABASE: keycloak
    depends_on:
      - db
    links:
      - db
    ports:
      - "9990:9990"
      - "9090:8080"
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432
