services:
- docker
language: java
jdk:
- openjdk11
branches:
  only:
  - master
  - "/^(\\d+\\.)?(\\d+\\.)?\\d+(-\\w+)?$/"
install: true
script:
- "${TRAVIS_BUILD_DIR}/scripts/travis-build.sh"
env:
  global:
  - secure: SH8SfVWb9+WB03HPB+BwCELJRyQW3LDXrqPSZj/mCISn2B7uiiDv9KhcznTv3y9zaq/kUfLAd2ecUWg/6quuHs1ZKvL+Ehj9BEzTmgYFHPDiqAVtafhgNgCSCEEiwjjIxU9PUAIkQYng4eIcrCEaTyzr4fqsg7QO+1YucUIqOMooqcJp3W5UpU5wkwqlnks1bmyHMyBvhGkU2S+W/D8ARy+Or+Vwb68n2ADTl6TCbvMf+dGYMbNs2AME+vEAcx9iS/PbkiC8BDkW35mRmnh+abT6HcRB3DA54nlHbUHRWhNdA7WRPKDzB7DIvfW62ZQpUdZdp3fd1+073dSwgYWtcngUlS6pkF6azxRHHEP/Mk3Q8TRbEY5PlPqeQEbuz8K4PVyrwv5vJBxo7dCuns7w2l+ZPLNil4ve2YLwjO4Q04RHpFwFOBTJ+6GNmM9EmjsmIRfvTAwKbKAsktCGK/cVkyVWmz5uKctUPrVzE64VjtH5iUSSvcHmo1a/FTfgrwvU1p3zmstsFiamiQe2ODKgQeFx3tA0IoBRg4PaAtuopkDaxteg98kNm0n0HiRB8oLmK2TXmFv6Y6so924VQ3j4UXYGMjwS0kfCVvkh7kgKCt2WSZEcL+0dkj3/l6Jd6V/p5/xue145AR7bI7GPn3y+Uypuk2SgiMCck+vBmM0c9Dg=
  - secure: BCgl+Spuz3gKRJ5q+cyehhKwFwaONwaTrFufVJ1nxLWqob5Mg9mYRsQLV/hJFcyXbs43Y3ApG0J1uB8SO64roWkkFh5Zlj1eMoHS5PXeIrJhkmjXr98VoHP5dgmxhqLdDo/9kynAOjC11UoJTLMst0+TiOYBzhoPSbbH75Tuur66mQfN+ufFaWEkxnqslP2R5/PmFQnfLvUXzvpJgWv5PAbtHwr4KLTO4kYnYmP+wwn9sFq6JR0DBbdU6BpIoTip5TZMqmSnPV4WhzHxArq2OUvFg4xcF4m5LHQfAz8hFMwiK1TgsdKDOTATiwdBxWwpzQaqZPVFXdaE1EOS/1Vb1LNRkJBplKgDIgTvvApdtF+LEAauMRxP/rkEsqW5FOqUxG3tqtkNV5jA7sqTHP74i8zT+NO+G1EpcfP9biacV2M1XsR4X6ATSCGPPep4Quw5T1sdoUn7+yLxCBeb+I1NVoWN68CikN5WUVzfXnh7dQnMFkF0r/KTEwtg9KeOOuRiKQTeDoaQqODoqhBFFElYnPUed28lvplYWgentqBU37Evrf0RRTiydcImYrmfeRF4jypmdDL2IkpLHJAWQc6YhYUGKnhVmzSElskDCoYlc2FnQbPHn6iFGVgl1QRAtI671VEg8DhbkBxDx8pGi4uPcDEYqCjxps7VWc4Vtwk8JSE=
