apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: payment-sdk-backend
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: payment-sdk-backend
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "${KUBE_INGRESS_STATIC_IP_NAME}"
    ingress.gcp.kubernetes.io/pre-shared-cert: "payment-dev"
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: payment-dashboard
    servicePort: 80
  rules:
    - host: payment-dev.mblb.net
      http:
        paths:
          - path: /api/*
            backend:
              serviceName: payment-sdk-backend
              servicePort: 80