apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-sdk-backend
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: payment-sdk-backend
data:
  JAVA_OPTS: ${KUBE_WS_CONFIGMAP_JAVA_OPTS}
  SPRING_PROFILES_ACTIVE: ${KUBE_WS_CONFIGMAP_SPRING_PROFILE}
  DB_PORT: "${KUBE_WS_CONFIGMAP_DB_PORT}"
  DB_HOST: ${KUBE_WS_CONFIGMAP_DB_HOST}
  DB_NAME: ${KUBE_WS_CONFIGMAP_DB_NAME}
  SENDGRID_PORT: ${KUBE_WS_SENDGRID_PORT}
  SENDGRID_ADDRESS: ${KUBE_WS_SENDGRID_ADDRESS}