FROM jboss/keycloak:4.8.3.Final
# RUN mkdir import
# COPY import /import
# Use this command to generate and export new initial data for Keycloak.
# CMD ["-b", "0.0.0.0", "-Dkeycloak.migration.action=export", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=./"]
# CMD ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/import", "-Dkeycloak.migration.strategy=IGNORE_EXISTING"]