package com.mobilabsolutions.payment.data.domain

import com.mobilabsolutions.payment.data.enum.PaymentMethod
import com.mobilabsolutions.payment.data.enum.PaymentServiceProvider
import org.hibernate.annotations.Type
import org.springframework.data.util.ProxyUtils
import java.util.*
import javax.persistence.*

/**
 * @author <a href="mailto:jovana@mobilabsolutions.com">Jovana Veskovic</a>
 */
@Entity
@Table(name = "alias")
class Alias : AutoGeneratedIdTimeAuditable() {

    @Id
    @Column(name = "id", length = 20)
    var id: String? = null

    @Column(name = "psp_alias")
    var pspAlias: String? = null

    @Column(name = "active")
    var active: Boolean = true

    @Lob
    @Type(type = "org.hibernate.type.TextType")
    @Column(name = "extra")
    var extra: String? = null

    @Enumerated(EnumType.STRING)
    @Column(name = "psp")
    var psp: PaymentServiceProvider? = null

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method")
    var paymentMethod: PaymentMethod? = null

    @ManyToOne
    @JoinColumn(name = "merchant_id", nullable = false, foreignKey = ForeignKey(name = "fk_merchant_alias"))
    var merchant: Merchant = Merchant()

    override fun hashCode(): Int {
        var hash = 7
        hash = 97 * hash + Objects.hashCode(this.id)
        return hash
    }

    override fun equals(other: Any?): Boolean {
        other ?: return false

        if (this === other) return true

        if (javaClass != ProxyUtils.getUserClass(other)) return false

        other as Alias

        return this.id == other.id
    }

    override fun toString(): String {
        return "Alias [pspAlias=$pspAlias, active=$active, extra=$extra, paymentMethod=$paymentMethod, psp=$psp, " +
                "merchant=$merchant]"
    }
}