package com.mobilabsolutions.payment.data

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.ForeignKey
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table

/**
 * @author <a href="mailto:mohamed.osman@mobilabsolutions.com">Mohamed Osman</a>
 */
@Entity
@Table(name = "filter")
class Filter(
    @Id
    @Column(name = "id", length = 20)
    var id: String? = null,

    @Column(name = "start_date")
    var createdAtStart: String? = null,

    @Column(name = "end_date")
    var createdAtEnd: String? = null,

    @Column(name = "status")
    var status: String? = null,

    @Column(name = "payment_method")
    var paymentMethod: String? = null,

    @Column(name = "text")
    var text: String? = null,

    @Column(name = "currency")
    var currency: String? = null,

    @Column(name = "amount")
    var amount: String? = null,

    @Column(name = "customer_id")
    var customerId: String? = null,

    @Column(name = "transaction_id")
    var transactionId: String? = null,

    @Column(name = "merchant_transaction_id")
    var merchantTransactionId: String? = null,

    @ManyToOne
    @JoinColumn(name = "merchant_id", nullable = false, foreignKey = ForeignKey(name = "fk_merchant_filter"))
    var merchant: Merchant = Merchant()
) : AutoGeneratedIdTimeAuditable() {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Filter

        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        return id?.hashCode() ?: 0
    }
}
