/*
 * Copyright © MobiLab Solutions GmbH
 */

package com.mobilabsolutions.payment.data

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import org.hibernate.annotations.Type
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Lob
import javax.persistence.Table

/**
 * @author <a href="mailto:jovana@mobilabsolutions.com">Jovana Veskovic</a>
 */
@Entity
@Table(name = "merchant")
class Merchant(
    @Id
    @Column(name = "id")
    var id: String? = null,

    @Column(name = "name")
    var name: String? = null,

    @Column(name = "email")
    var email: String? = null,

    @Lob
    @Column(name = "logo")
    var logo: ByteArray? = null,

    @Lob
    @Type(type = "org.hibernate.type.TextType")
    @Column(name = "psp_config")
    var pspConfig: String? = null,

    @Column(name = "default_currency_id", length = 3)
    var defaultCurrency: String? = null,

    @Column(name = "time_zone")
    var timezone: String? = null,

    @Column(name = "webhook_url")
    var webhookUrl: String? = null,

    @Column(name = "webhook_username")
    var webhookUsername: String? = null,

    @Column(name = "webhook_password")
    var webhookPassword: String? = null
) : AutoGeneratedIdTimeAuditable() {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Merchant

        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        return id?.hashCode() ?: 0
    }
}
