/*
 * Copyright © MobiLab Solutions GmbH
 */

package com.mobilabsolutions.payment.data

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import com.mobilabsolutions.payment.data.enum.KeyType
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.EnumType
import javax.persistence.Enumerated
import javax.persistence.ForeignKey
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id
import javax.persistence.JoinColumn
import javax.persistence.ManyToOne
import javax.persistence.Table

/**
 * @author <a href="mailto:jovana@mobilabsolutions.com">Jovana Veskovic</a>
 */
@Entity
@Table(name = "merchant_api_key")
class MerchantApiKey(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    val id: Long? = null,

    @Column(name = "name")
    var name: String? = null,

    @Column(name = "key")
    var key: String? = null,

    @Column(name = "active")
    var active: Boolean = true,

    @Enumerated(EnumType.STRING)
    @Column(name = "key_type")
    var keyType: KeyType? = null,

    @ManyToOne(optional = false)
    @JoinColumn(name = "merchant_id", nullable = false, foreignKey = ForeignKey(name = "fk_merchant_merchantapikey"))
    var merchant: Merchant = Merchant()
) : AutoGeneratedIdTimeAuditable() {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as MerchantApiKey

        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        return id?.hashCode() ?: 0
    }
}
