/*
 * Copyright © MobiLab Solutions GmbH
 */

package com.mobilabsolutions.payment.braintree.exception

import com.mobilabsolutions.server.commons.exception.PaymentError

/**
 * @author <a href("mailto:jovana@mobilabsolutions.com">Jovana Veskovic</a>
 */
enum class BraintreeErrors(val code: String, val error: PaymentError) {

    // Auth errors
    SETTLEMENT_DECLINED("4001", PaymentError.PAYMENT_ERROR),
    ALREADY_CAPTURED("4003", PaymentError.PAYMENT_ERROR),
    ALREADY_REFUNDED("4004", PaymentError.PAYMENT_ERROR),
    PAYPAL_RISK_REJECTED("4005", PaymentError.PAYMENT_ERROR),
    CAPTURE_AMOUNT_EXEECED("4006", PaymentError.PAYMENT_ERROR),
    PAYPAL_PENDING_NOT_SUPPORTED("4018", PaymentError.PAYMENT_ERROR),
    PAYPAL_REFUND_OPEN_NOT_ALLOWED("4019", PaymentError.REFUND_ERROR),
    PAYPAL_REFUND_ATTEMPT_LIMIT("4020", PaymentError.REFUND_ERROR),
    PAYPAL_REFUND_NOT_ALLOWED("4021", PaymentError.REFUND_ERROR),
    PAYPAL_REFUND_INVALID_PARTIAL("4022", PaymentError.REFUND_ERROR),
    PAYPAL_REFUND_MISSING_MERCHANT_ACH("4023", PaymentError.REFUND_ERROR),

    // Preauth errors
    EXPIRED_CARD("2004", PaymentError.PAYMENT_ERROR),
    INVALID_CARD_NUMBER("2005", PaymentError.PAYMENT_ERROR),
    INVALID_EXPIRATION_DATE("2006", PaymentError.PAYMENT_ERROR),
    CARD_ACCOUNT_LENGTH_ERROR("2008", PaymentError.PAYMENT_ERROR),
    NO_SUCH_ISSUER("2009", PaymentError.PAYMENT_ERROR),
    ISSUER_DECLINED("2010", PaymentError.PAYMENT_ERROR),
    VOICE_AUTHORIZATION_REQUIRED("2011", PaymentError.PAYMENT_ERROR),
    POSSIBLE_LOST_CARD("2012", PaymentError.PAYMENT_ERROR),
    POSSIBLE_STOLEN_CARD("2013", PaymentError.PAYMENT_ERROR),
    FRAUD_SUSPECTED("2014", PaymentError.PAYMENT_ERROR),
    TRANSACTION_NOT_ALLOWED("2015", PaymentError.PAYMENT_ERROR),
    CARDHOLDER_STOPPED_BILLING("2017", PaymentError.PAYMENT_ERROR),
    CARDHOLDER_STOPPED_ALL_BILLING("2018", PaymentError.PAYMENT_ERROR),
    INVALID_TRANSACTION("2019", PaymentError.PAYMENT_ERROR),
    VIOLATION("2020", PaymentError.PAYMENT_ERROR),
    SECURITY_VIOLATION("2021", PaymentError.PAYMENT_ERROR),
    UPDATED_CARDHOLDER_AVAILABLE("2022", PaymentError.PAYMENT_ERROR),
    NOT_SUPPORTED_FEATURE("2023", PaymentError.PAYMENT_ERROR),
    ENCRYPTION_ERROR("2031", PaymentError.PAYMENT_ERROR),
    SURCHARGE_NOT_PERMITTED("2032", PaymentError.PAYMENT_ERROR),
    INCONSISTENT_DATA("2033", PaymentError.PAYMENT_ERROR),
    NO_ACTION_TAKEN("2034", PaymentError.PAYMENT_ERROR),
    AUTHORIZATION_NOT_FOUND_TO_REVERSE("2036", PaymentError.PAYMENT_ERROR),
    ALREADY_REVERSED("2037", PaymentError.PAYMENT_ERROR),
    INVALID_AUTHORIZATION_CODE("2039", PaymentError.PAYMENT_ERROR),
    DECLINED_CALL_FOR_APROVAL("2041", PaymentError.PAYMENT_ERROR),
    DO_NOT_RETRY("2043", PaymentError.PAYMENT_ERROR),
    DECLINED_CALL_ISSUER("2044", PaymentError.PAYMENT_ERROR),
    CALL_ISSUER_PICK_UP_CARD("2047", PaymentError.PAYMENT_ERROR),
    INVALID_SKU_NUMBER("2049", PaymentError.PAYMENT_ERROR),
    INVALID_CREDIT_PLAN("2050", PaymentError.PAYMENT_ERROR),
    CREDIT_CARD_NUMBER_DOES_NOT_MATCH("2051", PaymentError.PAYMENT_ERROR),
    INVALID_LEVEL_III_PURCHASE("2052", PaymentError.PAYMENT_ERROR),
    CARD_LOST_OR_STOLEN("2053", PaymentError.PAYMENT_ERROR),
    REVERSAL_AMOUNT_DOES_NOT_MATCH("2054", PaymentError.PAYMENT_ERROR),
    NO_MASTER_CARD_SECURE_CODE_ENABLED("2058", PaymentError.PAYMENT_ERROR),
    ADDRESS_VERIFICATION_FAILED("2059", PaymentError.PAYMENT_ERROR),
    ADDRESS_VERIFICATION_AND_CARD_SECURITY_CODE_FAILED("2060", PaymentError.PAYMENT_ERROR),
    INVALID_TRANSACTION_DATE("2061", PaymentError.PAYMENT_ERROR),
    INVALID_TAX_AMOUNT("2062", PaymentError.PAYMENT_ERROR),
    PAYPAL_BUSINESS_ACCOUNT_PREFERENCE_RESULT_IN_TRANSACTION_FAILING("2063", PaymentError.PAYMENT_ERROR),
    INVALID_CURRENCY_CODE("2064", PaymentError.PAYMENT_ERROR),
    REFUND_TIME_LIMIT_EXCEEDED("2065", PaymentError.PAYMENT_ERROR),
    PAYPAL_BUSINESS_ACCOUNT_RESTRICTED("2066", PaymentError.PAYMENT_ERROR),
    AUTHORIZATION_EXPIRED("2067", PaymentError.PAYMENT_ERROR),
    PAYPAL_BUSINESS_ACCOUNT_LOCKED_OR_CLOSED("2068", PaymentError.PAYMENT_ERROR),
    PAYPAL_BLOCKING_DUPLICATE_ORDER_IDS("2069", PaymentError.PAYMENT_ERROR),
    PAYPAL_BUYER_REVOKED_PAYMENT_AUTHORIZATION("2070", PaymentError.PAYMENT_ERROR),
    PAYPAL_PAYEE_ACCOUNT_INVALID("2071", PaymentError.PAYMENT_ERROR),
    PAYPAL_PAYEE_EMAIL_INCORRECTLY_FORMATED("2072", PaymentError.PAYMENT_ERROR),
    PAYPAL_VALIDATION_ERROR("2073", PaymentError.PAYMENT_ERROR),
    FUNDING_INSTRUMENT_WAS_DECLINED("2074", PaymentError.PAYMENT_ERROR),
    PAYER_ACCOUNT_LOCKED_OR_CLOSED("2075", PaymentError.PAYMENT_ERROR),
    PAYER_CANNOT_PAY_WITH_PAYPAL("2076", PaymentError.PAYMENT_ERROR),
    TRANSACTION_REFUSED_DUE_TO_PAYPAL_RISK_MODEL("2077", PaymentError.PAYMENT_ERROR),
    PAYPAL_MERCHANT_ACCOUNT_CONFIGURATION_ERROR("2078", PaymentError.PAYMENT_ERROR),
    DO_NOT_HONOR("2000", PaymentError.PAYMENT_ERROR),
    INSUFFICIENT_FUNDS("2001", PaymentError.PAYMENT_ERROR),
    LIMIT_EXCEEDED("2002", PaymentError.PAYMENT_ERROR),
    CARDHOLDER_ACTIVITY_LIMIT_EXCEEDED("2003", PaymentError.PAYMENT_ERROR),
    DUPLICATE_TRANSACTION("2016", PaymentError.PAYMENT_ERROR),
    CARD_TYPE_NOT_ENABLED("2024", PaymentError.PAYMENT_ERROR),
    SET_UP_ERROR_MERCHANT("2025", PaymentError.PAYMENT_ERROR),
    INVALID_MERCHANT_ID("2026", PaymentError.PAYMENT_ERROR),
    SET_UP_ERROR_AMOUNT("2027", PaymentError.PAYMENT_ERROR),
    SET_UP_ERROR_HIERARCHY("2028", PaymentError.PAYMENT_ERROR),
    SET_UP_ERROR_CARD("2029", PaymentError.PAYMENT_ERROR),
    SET_UP_ERROR_TERMINAL("2030", PaymentError.PAYMENT_ERROR),
    PARTIAL_APPROVAL_FOR_AMOUNT_GROUP_III_VERSION("2035", PaymentError.PAYMENT_ERROR),
    PROCESSOR_DECLINED("2038", PaymentError.PAYMENT_ERROR),
    INVALID_STORE("2040", PaymentError.PAYMENT_ERROR),
    INVALID_CLIENT_ID("2042", PaymentError.PAYMENT_ERROR),
    INVALID_MERCHANT_NUMBER("2045", PaymentError.PAYMENT_ERROR),
    DECLINED("2046", PaymentError.PAYMENT_ERROR),
    INVALID_AMOUNT("2048", PaymentError.PAYMENT_ERROR),
    INVALID_TRANSACTION_DIVISION_NUMBER("2055", PaymentError.PAYMENT_ERROR),
    TRANSACTION_AMOUNT_EXCEEDS_TRANSACTION_DIVISION_LIMIT("2056", PaymentError.PAYMENT_ERROR),
    RESTRICTION_ON_THE_CARD("2057", PaymentError.PAYMENT_ERROR),
    INVALID_SECURE_PAYMENT_DATA("2078", PaymentError.PAYMENT_ERROR);

    companion object {
        fun mapResponseCode(responseCode: String): PaymentError {
            return values().firstOrNull { it.code == responseCode }?.error ?: PaymentError.UNKNOWN_ERROR
        }
    }
}
