/*
 * Copyright © MobiLab Solutions GmbH
 */

package com.mobilabsolutions.payment.notifications.data

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import com.mobilabsolutions.payment.data.enum.NotificationStatus
import com.mobilabsolutions.payment.data.enum.PaymentServiceProvider
import org.hibernate.annotations.Type
import javax.persistence.Column
import javax.persistence.EmbeddedId
import javax.persistence.Entity
import javax.persistence.EnumType
import javax.persistence.Enumerated
import javax.persistence.Lob
import javax.persistence.Table

/**
 * @author <a href="mailto:doruk@mobilabsolutions.com">Doruk Coskun</a>
 */
@Entity
@Table(name = "notification")
class Notification(
    @EmbeddedId
    var notificationId: NotificationId,

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    var status: NotificationStatus? = null,

    @Lob
    @Type(type = "org.hibernate.type.TextType")
    @Column(name = "message")
    var message: String? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "psp")
    var psp: PaymentServiceProvider? = null
) : AutoGeneratedIdTimeAuditable() {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Notification

        if (notificationId != other.notificationId) return false

        return true
    }

    override fun hashCode(): Int {
        return notificationId.hashCode()
    }
}
