package com.mobilabsolutions.payment.notifications.data

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import com.mobilabsolutions.payment.data.enum.NotificationStatus
import com.mobilabsolutions.payment.data.enum.PaymentServiceProvider
import org.hibernate.annotations.Type
import org.springframework.data.util.ProxyUtils
import java.util.Objects
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.EnumType
import javax.persistence.Enumerated
import javax.persistence.Id
import javax.persistence.Lob
import javax.persistence.Table

/**
 * @author <a href="mailto:doruk@mobilabsolutions.com">Doruk Coskun</a>
 */
@Entity
@Table(name = "notification")
class Notification(
    @Id
    @Column(name = "id")
    var id: String? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    var status: NotificationStatus? = null,

    @Lob
    @Type(type = "org.hibernate.type.TextType")
    @Column(name = "message")
    var message: String? = null,

    @Enumerated(EnumType.STRING)
    @Column(name = "psp")
    var psp: PaymentServiceProvider? = null
) : AutoGeneratedIdTimeAuditable() {
    override fun hashCode(): Int {
        var hash = 7
        hash = 97 * hash + Objects.hashCode(this.id)
        return hash
    }

    override fun equals(other: Any?): Boolean {
        other ?: return false

        if (this === other) return true

        if (javaClass != ProxyUtils.getUserClass(other)) return false

        other as Notification

        return this.id == other.id
    }
}
