/*
 * Copyright © MobiLab Solutions GmbH
 */

package com.mobilabsolutions.payment.notifications.data.repository

import com.mobilabsolutions.payment.data.configuration.AutoGeneratedIdTimeAuditable
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

/**
 * * Simple entity used for testing custom repository functionality.
 *
 * @author <a href="mailto:jovana@mobilabsolutions.com">Jovana Veskovic</a>
 */
@Entity
class TestRecord : AutoGeneratedIdTimeAuditable() {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private val id: Long? = null

    var name: String? = null
    var quantity: Int = 0

    @Column(name = "record_order")
    var order: Int = 0
}
